name: pemdes_mekarjaya
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cloud_firestore: ^3.4.8
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.9.0
  firebase_core: ^1.21.1
  firebase_storage: ^10.3.8
  flutter_svg: ^1.1.5
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  flutter:
    sdk: flutter
  get: 4.6.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  maps_launcher: ^2.0.1
  syncfusion_flutter_datepicker: ^20.1.61
  flutter_barcode_scanner: ^2.0.0
  lottie: ^2.1.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  image_path: 'assets/images/logo.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900

